### ISSUE TITLE
Unable to build on heroku?

### ISSUE THREAD

**Issue by nicholasareed** [dockhero/heroku-buildpack-docker-compose#2]
This was working flawlessly for awhile, but now it fails: 

```
remote: -----> https://github.com/dockhero/heroku-buildpack-docker-compose.git app detected
remote: -----> Using docker CLI 18.09.0
remote: -----> Using docker-compose 1.23.1
remote: -----> Installing binaries under /app/vendor
remote:
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote: cp: cannot create regular file '/tmp/build_805166a88b8b676912afe8afa8d29926/vendor/docker/docker-compose': No such file or directory
remote: chmod: cannot access '/tmp/build_805166a88b8b676912afe8afa8d29926/vendor/docker/*': No such file or directory
remote: -----> Writing .profile.d script
remote: -----> Discovering process types
remote:        Procfile declares types -> web
```

My app.json contains the standard stuff for dockhero: 
```
  "image" : "heroku/nodejs",
  "buildpacks" : [
    {
      "url": "heroku/nodejs"
    },
    {
      "url": "https://github.com/dockhero/heroku-buildpack-docker-compose.git"
    }
  ],

  "addons": [
    "heroku-redis",
    "mongolab",
    "dockhero"
  ],
```

I'm not sure where the problem lies.

**Comment by nicholasareed** [comment]
Found a missing file. 

Buildpack looks for "-ce.tgz" at the end of the docker release, but on https://download.docker.com/linux/static/stable/x86_64/ 18.09.9 doesn't have that "-ce" suffix. 

But, that doesn't fix the issue, I still get the same errors and can't get docker cli or docker-compose functional.

**Comment by vovayartsev** [comment]
The issue was caused by the last item in the list of available versions at https://download.docker.com/linux/static/stable/x86_64/

```
...
docker-18.06.1-ce.tgz                                                               
docker-18.09.0.tgz     
```

I'm not sure whether they changed the naming schema or not.... Just for safety reason I added a `grep` statement which filters only "Community Edition" versions.

@nicholasareed Thanks for catching that!
